// sites/all/libraries/doka/presets/svelte/src/App.svelte
<script>

// svelte doka
import { DokaImageEditor, DokaImageEditorModal, DokaImageEditorOverlay } from 'svelte-doka';

// doka
import 'doka/doka.css';
import {
    // editor
    locale_en_gb,
    createDefaultImageReader,
    createDefaultImageWriter,

    // plugins
    setPlugins,
    plugin_crop,
    plugin_crop_locale_en_gb,
    plugin_crop_defaults,
    plugin_finetune,
    plugin_finetune_locale_en_gb,
    plugin_finetune_defaults,
    plugin_filter,
    plugin_filter_locale_en_gb,
    plugin_filter_defaults,
    plugin_decorate,
    plugin_decorate_defaults,
    plugin_decorate_locale_en_gb,
    component_shape_editor_locale_en_gb,
} from 'doka';

setPlugins(plugin_crop, plugin_finetune, plugin_filter, plugin_decorate);

const editorDefaults = {
    imageReader: createDefaultImageReader(),
    imageWriter: createDefaultImageWriter(),
    ...plugin_crop_defaults,
    ...plugin_finetune_defaults,
    ...plugin_filter_defaults,
    ...plugin_decorate_defaults,
    locale: {
        ...locale_en_gb,
        ...plugin_crop_locale_en_gb,
        ...plugin_finetune_locale_en_gb,
        ...plugin_filter_locale_en_gb,
        ...plugin_decorate_locale_en_gb,
        ...component_shape_editor_locale_en_gb,
    },
};


// props
let inlineResult;

// modal
let modalResult;
let modalVisible = false;

// overlay
let overlayVisible = false;
let overlayResult;
let overlayImageState;
</script>

<main>
	<h1>Doka Image Editor</h1>

	<h2>Inline</h2>

	<div style="height:70vh">
		<DokaImageEditor 
			{ ...editorDefaults }
			on:load={(e) => console.log('inline load', e.detail)}
			on:process={(e) => inlineResult = URL.createObjectURL(e.detail.dest)}
			src="image.jpeg" >
		</DokaImageEditor>
	</div>

	{#if inlineResult}
	<p>
		<img src={inlineResult} alt=""/>
	</p>
	{/if}

	<h2>Modal</h2>

	<p>
		<button on:click={() => modalVisible = true}>Open editor</button>
	</p>

	{#if modalVisible}
		<DokaImageEditorModal
			{ ...editorDefaults }
			on:hide={(e) => modalVisible = false}
			on:load={(e) => console.log('modal load', e.detail)}
			on:process={(e) => modalResult = URL.createObjectURL(e.detail.dest)}
			src="image.jpeg" >

		</DokaImageEditorModal>
	{/if}

	{#if modalResult}
	<p>
		<img src={modalResult} alt=""/>
	</p>
	{/if}

	<h2>Overlay</h2>

	<p>
		{#if !overlayVisible }
			<button on:click={() => overlayVisible = true}>Edit image</button>
		{:else}
			<button on:click={() => overlayVisible = false}>Close editor</button>
		{/if}
	</p>

	{#if !overlayVisible}
	<p>
		<img width="512" height="256" src={overlayResult || 'image.jpeg'} alt="" />
	</p>
	{:else}
	<div style="width:512px; height:256px;">
		<DokaImageEditorOverlay 
			{ ...editorDefaults }
			on:load={(e) => console.log('overlay load', e.detail)}
			on:process={(e) => {
				overlayImageState = e.detail.imageState;
				overlayResult = URL.createObjectURL(e.detail.dest)
				overlayVisible = false;
			}}
			src="image.jpeg" 
			imageState={overlayImageState}>
		</DokaImageEditorOverlay>
	</div>
	{/if}
	
</main>
<style>
	img {
		max-width: 100%;
	}
</style>

// sites/all/libraries/doka/presets/angular/v8/src/app/app.component.ts
import { Component } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

// doka
import {
    // editor
    locale_en_gb,
    createDefaultImageReader,
    createDefaultImageWriter,

    // plugins
    setPlugins,
    plugin_crop,
    plugin_crop_locale_en_gb,
    plugin_crop_defaults,
    plugin_finetune,
    plugin_finetune_locale_en_gb,
    plugin_finetune_defaults,
    plugin_filter,
    plugin_filter_locale_en_gb,
    plugin_filter_defaults,
    plugin_decorate,
    plugin_decorate_defaults,
    plugin_decorate_locale_en_gb,
    component_shape_editor_locale_en_gb,
} from '../../local_modules/doka';

setPlugins(plugin_crop, plugin_finetune, plugin_filter, plugin_decorate);

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: [],
})
export class AppComponent {
    constructor(private sanitizer: DomSanitizer) {}

    // editor generic state
    editorOptions: any = {
        imageReader: createDefaultImageReader(),
        imageWriter: createDefaultImageWriter(),
        ...plugin_crop_defaults,
        ...plugin_finetune_defaults,
        ...plugin_filter_defaults,
        ...plugin_decorate_defaults,
        locale: {
            ...locale_en_gb,
            ...plugin_crop_locale_en_gb,
            ...plugin_finetune_locale_en_gb,
            ...plugin_filter_locale_en_gb,
            ...plugin_decorate_locale_en_gb,
            ...component_shape_editor_locale_en_gb,
        },
    };

    // inline
    inlineSrc: string = 'assets/image.jpeg';
    inlineResult: string = undefined;

    handleInlineLoad($event) {
        console.log('inline load', $event);
    }

    handleInlineProcess($event) {
        console.log('inline process', $event);
        const objectURL = URL.createObjectURL($event.dest);
        this.inlineResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
    }

    // modal
    modalSrc: string = 'assets/image.jpeg';
    modalResult: string = undefined;
    modalVisible: boolean = false;

    handleModalLoad($event) {
        console.log('modal load', $event);
    }

    handleModalProcess($event) {
        console.log('modal process', $event);
        const objectURL = URL.createObjectURL($event.dest);
        this.modalResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
    }

    // overlay
    overlaySrc: string = 'assets/image.jpeg';
    overlayVisible: boolean = false;
    overlayResult: string = undefined;
    overlayOptions: any = {
        imageReader: createDefaultImageReader(),
        imageWriter: createDefaultImageWriter(),
        locale: {
            ...locale_en_gb,
            ...plugin_crop_locale_en_gb,
        },
    };

    handleOverlayLoad($event) {
        console.log('overlay load', $event);
    }

    handleOverlayProcess($event) {
        const objectURL = URL.createObjectURL($event.dest);
        this.overlayResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
        this.overlayOptions = {
            ...this.overlayOptions,
            imageState: $event.imageState,
        };

        this.overlayVisible = false;
    }
}
